### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by ghost** [christophgockel/atom-sftp-sync#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [Atom-SFTP-sync](https://github.com/christophgockel/atom-sftp-sync) package 2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/liyuangao/.atom/packages/Atom-SFTP-sync/lib/DeploymentManager.js:196

TypeError: Cannot read property 'path' of undefined
    at DeploymentManager.uploadCurrentFile (/packages/Atom-SFTP-sync/lib/DeploymentManager.js:196:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1388:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:10.1.0 core:confirm (input.hidden-input)
     -0:16.6.0 atom-sftp-sync:uploadCurrentFile (div.lines)
```

### Non-Core Packages

```
atom-eclipse-syntax 0.0.5 
atom-ftp-deployment 0.4.0 
Atom-SFTP-sync 2.0.1 
simplified-chinese-menu 5.3.5 
```

**Comment by christophgockel** [comment]
Thanks @lygao for the report!
Sorry that you see that error message, but can I ask you for steps to reproduce it?
At the moment I only have a hunch that you currently don't have a project set up in Atom. Is that possible that you tried the plugin only after opening a single file?

Currently Atom SFTP sync assumes that it runs in an atom project or more specifically that you opened a directory and want to use the sync functionality for that. Not just a single file.

**Comment by EmbDclic** [comment]
Hello @christophgockel 

I have the same error message and it shows indeed when I open a single file without having a project setup. Is there a way to bypass this alert and be able to save the file anyway (on my local hard drive), or do I have to open a project everytime?
I frequently use the edit function of FileZilla when I just want to edit a single file on my server. Atom opens a new window and there is no project setup in that case, and therefore I see this error of Atom SFTP.

For the rest, your plugin works very well. Thanks!
