### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by giuseppelamatrice** [christophgockel/atom-sftp-sync#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.6
**Thrown From**: [Atom-SFTP-sync](https://github.com/christophgockel/atom-sftp-sync) package 2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/giuseppelamatrice/.atom/packages/Atom-SFTP-sync/lib/DeploymentManager.js:217

TypeError: Cannot read property 'path' of undefined
    at DeploymentManager.uploadOnSave (/packages/Atom-SFTP-sync/lib/DeploymentManager.js:217:39)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350065)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212791)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208925)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285300)
```

### Commands

```
     -0:12.5.0 core:paste (input.hidden-input)
     -0:10.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ftp-editor 0.5.0 
Atom-SFTP-sync 2.0.1 
```

**Comment by SwatiCharter** [comment]
I am facing same issue -
Uncaught TypeError: Cannot read property 'path' of undefined
ypeError: Cannot read property 'path' of undefined
    at DeploymentManager.uploadOnSave (/Users/spachpute/.atom/packages/Atom-SFTP-sync/lib/DeploymentManager.js:217:39)
    at CommandRegistry.handleCommandEvent (/private/var/folders/3_/smjs7zfs09b2hf5kf1qxxnsc0000gn/T/AppTranslocation/3EB92AA8-00B7-4D4F-81C3-D8F5D34FFD5E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (/private/var/folders/3_/smjs7zfs09b2hf5kf1qxxnsc0000gn/T/AppTranslocation/3EB92AA8-00B7-4D4F-81C3-D8F5D34FFD5E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/3_/smjs7zfs09b2hf5kf1qxxnsc0000gn/T/AppTranslocation/3EB92AA8-00B7-4D4F-81C3-D8F5D34FFD5E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/3_/smjs7zfs09b2hf5kf1qxxnsc0000gn/T/AppTranslocation/3EB92AA8-00B7-4D4F-81C3-D8F5D34FFD5E/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284329

**Comment by EmbDclic** [comment]
**Steps to reproduce:**

1. Open a project in Atom which has an **atom-sftp-sync.json** file with `"uploadOnSave": true`
2. Open a file that is not in the project folder (e.g. opening a PHP file of another folder from the Windows explorer)
3. Editing and saving this file

**Comment by pvanallen** [comment]
I also see this error if the file to be saved is not in the directory that is configured with atom-sftp-sync.json

**Comment by christophgockel** [comment]
Thank you @giuseppelamatrice (and @EmbDclic) for the report. Not sure if you're still experiencing the issue or since then have moved on to a different solution. I only noticed that at the time of submitting the issue you've used an older version than the latest that was/is available.
If you still experience the issue with the current version `2.1.0` please raise a new issue.

To @pvanallen: Yeah good point! This is something we've missed handling so far. In the next release we're going to be less invasive and just ignore the projects and directories where no config file could be found.

**Comment by EmbDclic** [comment]
@christophgockel I still had the problem, but as suggested I updated to the last version and it solved the problem. Thank you!

**Comment by zedrdave** [comment]
I'm on the latest version and still seeing this problem…
